
:: CI artifact paths.
set UI_ROOT_ARTIFACTS_PATH=%~dp0.\..\..\..\Publish\Artifacts\Build\

set UI_WINDOWS_ARTIFACTS_PATH=%UI_ROOT_ARTIFACTS_PATH%\Windows\UI\
set UI_MACOS_ARTIFACTS_PATH=%UI_ROOT_ARTIFACTS_PATH%\macOS\UI\
set UI_LINUX_ARTIFACTS_PATH=%UI_ROOT_ARTIFACTS_PATH%\Linux\UI\

set UI_PAL_WINDOWS_ARTIFACTS_PATH=%UI_WINDOWS_ARTIFACTS_PATH%\PAL
set UI_PAL_MACOS_ARTIFACTS_PATH=%UI_MACOS_ARTIFACTS_PATH%\PAL
set UI_PAL_LINUX_ARTIFACTS_PATH=%UI_LINUX_ARTIFACTS_PATH%\PAL

:: Build bin directories.

set UI_WINDOWS_PAL_BIN=%SCRIPT_HOME%\..\Alternet.UI.Pal\bin\Windows\x64\Release
set UI_MACOS_PAL_BIN=%SCRIPT_HOME%\..\Alternet.UI.Pal\bin\MacOS\x64\Release
set UI_LINUX_PAL_BIN=%SCRIPT_HOME%\..\Alternet.UI.Pal\bin\Linux\x64\Release

exit /b 0