// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2024 AlterNET Software.</auto-generated>

#pragma once

#include "AuiDefaultTabArt.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API AuiDefaultTabArt* AuiDefaultTabArt_Create_()
{
    #if !defined(__WXMSW__)
    return MarshalExceptions<AuiDefaultTabArt*>([&](){
    #endif
        return new AuiDefaultTabArt();
    #if !defined(__WXMSW__)
    });
    #endif
}

