// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2024 AlterNET Software.</auto-generated>

#pragma once

#include "AuiToolBarItem.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API AuiToolBarItem* AuiToolBarItem_Create_()
{
    #if !defined(__WXMSW__)
    return MarshalExceptions<AuiToolBarItem*>([&](){
    #endif
        return new AuiToolBarItem();
    #if !defined(__WXMSW__)
    });
    #endif
}

