using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Alternet.Drawing
{
    internal enum WxSystemColour
    {
        SYS_COLOUR_SCROLLBAR,
        SYS_COLOUR_DESKTOP,
        SYS_COLOUR_ACTIVECAPTION,
        SYS_COLOUR_INACTIVECAPTION,
        SYS_COLOUR_MENU,
        SYS_COLOUR_WINDOW,
        SYS_COLOUR_WINDOWFRAME,
        SYS_COLOUR_MENUTEXT,
        SYS_COLOUR_WINDOWTEXT,
        SYS_COLOUR_CAPTIONTEXT,
        SYS_COLOUR_ACTIVEBORDER,
        SYS_COLOUR_INACTIVEBORDER,
        SYS_COLOUR_APPWORKSPACE,
        SYS_COLOUR_HIGHLIGHT,
        SYS_COLOUR_HIGHLIGHTTEXT,
        SYS_COLOUR_BTNFACE,
        SYS_COLOUR_BTNSHADOW,
        SYS_COLOUR_GRAYTEXT,
        SYS_COLOUR_BTNTEXT,
        SYS_COLOUR_INACTIVECAPTIONTEXT,
        SYS_COLOUR_BTNHIGHLIGHT,
        SYS_COLOUR_3DDKSHADOW,
        SYS_COLOUR_3DLIGHT,
        SYS_COLOUR_INFOTEXT,
        SYS_COLOUR_INFOBK,
        SYS_COLOUR_LISTBOX,
        SYS_COLOUR_HOTLIGHT,
        SYS_COLOUR_GRADIENTACTIVECAPTION,
        SYS_COLOUR_GRADIENTINACTIVECAPTION,
        SYS_COLOUR_MENUHILIGHT,
        SYS_COLOUR_MENUBAR,
        SYS_COLOUR_LISTBOXTEXT,
        SYS_COLOUR_LISTBOXHIGHLIGHTTEXT,

        SYS_COLOUR_MAX,

        // synonyms
        SYS_COLOUR_BACKGROUND = SYS_COLOUR_DESKTOP,
        SYS_COLOUR_3DFACE = SYS_COLOUR_BTNFACE,
        SYS_COLOUR_3DSHADOW = SYS_COLOUR_BTNSHADOW,
        SYS_COLOUR_BTNHILIGHT = SYS_COLOUR_BTNHIGHLIGHT,
        SYS_COLOUR_3DHIGHLIGHT = SYS_COLOUR_BTNHIGHLIGHT,
        SYS_COLOUR_3DHILIGHT = SYS_COLOUR_BTNHIGHLIGHT,
        SYS_COLOUR_FRAMEBK = SYS_COLOUR_BTNFACE,
    }
}
