// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2023.</auto-generated>
#nullable enable
#pragma warning disable

using System;
using System.Runtime.InteropServices;
using System.ComponentModel;
using System.Security;
namespace Alternet.UI.Native
{
    internal class Application : NativeObject
    {
        static Application()
        {
            SetEventCallback();
        }
        
        public Application()
        {
            SetNativePointer(NativeApi.Application_Create_());
        }
        
        public Application(IntPtr nativePointer) : base(nativePointer)
        {
        }
        
        public string Name
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetName_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetName_(NativePointer, value);
            }
        }
        
        public Keyboard Keyboard
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetKeyboard_(NativePointer);
                var m = NativeObject.GetFromNativePointer<Keyboard>(n, p => new Keyboard(p))!;
                ReleaseNativeObjectPointer(n);
                return m;
            }
            
        }
        
        public Mouse Mouse
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetMouse_(NativePointer);
                var m = NativeObject.GetFromNativePointer<Mouse>(n, p => new Mouse(p))!;
                ReleaseNativeObjectPointer(n);
                return m;
            }
            
        }
        
        public Clipboard Clipboard
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetClipboard_(NativePointer);
                var m = NativeObject.GetFromNativePointer<Clipboard>(n, p => new Clipboard(p))!;
                ReleaseNativeObjectPointer(n);
                return m;
            }
            
        }
        
        public string DisplayName
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetDisplayName_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetDisplayName_(NativePointer, value);
            }
        }
        
        public string AppClassName
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetAppClassName_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetAppClassName_(NativePointer, value);
            }
        }
        
        public string VendorName
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetVendorName_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetVendorName_(NativePointer, value);
            }
        }
        
        public string VendorDisplayName
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetVendorDisplayName_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetVendorDisplayName_(NativePointer, value);
            }
        }
        
        public bool InUixmlPreviewerMode
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetInUixmlPreviewerMode_(NativePointer);
                var m = n;
                return m;
            }
            
            set
            {
                CheckDisposed();
                NativeApi.Application_SetInUixmlPreviewerMode_(NativePointer, value);
            }
        }
        
        public bool InvokeRequired
        {
            get
            {
                CheckDisposed();
                var n = NativeApi.Application_GetInvokeRequired_(NativePointer);
                var m = n;
                return m;
            }
            
        }
        
        public static void SetSystemOptionInt(string name, int value)
        {
            NativeApi.Application_SetSystemOptionInt_(name, value);
        }
        
        public void Run(Window window)
        {
            CheckDisposed();
            NativeApi.Application_Run_(NativePointer, window.NativePointer);
        }
        
        public void WakeUpIdle()
        {
            CheckDisposed();
            NativeApi.Application_WakeUpIdle_(NativePointer);
        }
        
        public void Exit()
        {
            CheckDisposed();
            NativeApi.Application_Exit_(NativePointer);
        }
        
        public static void SuppressDiagnostics(int flags)
        {
            NativeApi.Application_SuppressDiagnostics_(flags);
        }
        
        public void BeginInvoke(System.Action action)
        {
            CheckDisposed();
            var actionCallbackHandle = new GCHandle();
            var actionSink = new NativeApi.PInvokeCallbackActionType(
                () =>
                {
                    action();
                    actionCallbackHandle.Free();
                });
            actionCallbackHandle = GCHandle.Alloc(actionSink);
            NativeApi.Application_BeginInvoke_(NativePointer, actionSink);
        }
        
        static GCHandle eventCallbackGCHandle;
        
        static void SetEventCallback()
        {
            if (!eventCallbackGCHandle.IsAllocated)
            {
                var sink = new NativeApi.ApplicationEventCallbackType((obj, e, parameter) =>
                UI.Application.HandleThreadExceptions(() =>
                {
                    var w = NativeObject.GetFromNativePointer<Application>(obj, p => new Application(p));
                    if (w == null) return IntPtr.Zero;
                    return w.OnEvent(e, parameter);
                }
                ));
                eventCallbackGCHandle = GCHandle.Alloc(sink);
                NativeApi.Application_SetEventCallback_(sink);
            }
        }
        
        IntPtr OnEvent(NativeApi.ApplicationEvent e, IntPtr parameter)
        {
            switch (e)
            {
                case NativeApi.ApplicationEvent.Idle:
                {
                    Idle?.Invoke(this, EventArgs.Empty); return IntPtr.Zero;
                }
                default: throw new Exception("Unexpected ApplicationEvent value: " + e);
            }
        }
        
        public event EventHandler? Idle;
        
        [SuppressUnmanagedCodeSecurity]
        public class NativeApi : NativeApiProvider
        {
            static NativeApi() => Initialize();
            
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            public delegate IntPtr ApplicationEventCallbackType(IntPtr obj, ApplicationEvent e, IntPtr param);
            
            public enum ApplicationEvent
            {
                Idle,
            }
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetEventCallback_(ApplicationEventCallbackType callback);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr Application_Create_();
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern string Application_GetName_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetName_(IntPtr obj, string value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr Application_GetKeyboard_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr Application_GetMouse_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr Application_GetClipboard_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern string Application_GetDisplayName_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetDisplayName_(IntPtr obj, string value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern string Application_GetAppClassName_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetAppClassName_(IntPtr obj, string value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern string Application_GetVendorName_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetVendorName_(IntPtr obj, string value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern string Application_GetVendorDisplayName_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetVendorDisplayName_(IntPtr obj, string value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern bool Application_GetInUixmlPreviewerMode_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetInUixmlPreviewerMode_(IntPtr obj, bool value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern bool Application_GetInvokeRequired_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SetSystemOptionInt_(string name, int value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_Run_(IntPtr obj, IntPtr window);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_WakeUpIdle_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_Exit_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_SuppressDiagnostics_(int flags);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void Application_BeginInvoke_(IntPtr obj, PInvokeCallbackActionType action);
            
        }
    }
}
