// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2026 AlterNET Software.</auto-generated>
#nullable enable
#pragma warning disable

using System;
using System.Runtime.InteropServices;
using System.ComponentModel;
using System.Security;
namespace Alternet.UI.Native
{
    internal partial class ImageList : NativeObject
    {
        static ImageList()
        {
        }
        
        public ImageList()
        {
            SetNativePointer(NativeApi.ImageList_Create_());
        }
        
        public ImageList(IntPtr nativePointer) : base(nativePointer)
        {
        }
        
        public Alternet.Drawing.SizeI PixelImageSize
        {
            get
            {
                CheckDisposed();
                return NativeApi.ImageList_GetPixelImageSize_(NativePointer);
            }
            
            set
            {
                CheckDisposed();
                NativeApi.ImageList_SetPixelImageSize_(NativePointer, value);
            }
        }
        
        public Alternet.Drawing.SizeD ImageSize
        {
            get
            {
                CheckDisposed();
                return NativeApi.ImageList_GetImageSize_(NativePointer);
            }
            
            set
            {
                CheckDisposed();
                NativeApi.ImageList_SetImageSize_(NativePointer, value);
            }
        }
        
        public void AddImage(Image image)
        {
            CheckDisposed();
            NativeApi.ImageList_AddImage_(NativePointer, image.NativePointer);
        }
        
        public bool Remove(int index)
        {
            CheckDisposed();
            return NativeApi.ImageList_Remove_(NativePointer, index);
        }
        
        public bool Clear()
        {
            CheckDisposed();
            return NativeApi.ImageList_Clear_(NativePointer);
        }
        
        
        [SuppressUnmanagedCodeSecurity]
        public class NativeApi : NativeApiProvider
        {
            static NativeApi() => Initialize();
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr ImageList_Create_();
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern Alternet.Drawing.SizeI ImageList_GetPixelImageSize_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void ImageList_SetPixelImageSize_(IntPtr obj, Alternet.Drawing.SizeI value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern Alternet.Drawing.SizeD ImageList_GetImageSize_(IntPtr obj);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void ImageList_SetImageSize_(IntPtr obj, Alternet.Drawing.SizeD value);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern void ImageList_AddImage_(IntPtr obj, IntPtr image);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern bool ImageList_Remove_(IntPtr obj, int index);
            
            [DllImport(NativeModuleName, CallingConvention = CallingConvention.Cdecl)]
            public static extern bool ImageList_Clear_(IntPtr obj);
            
        }
    }
}
