// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2026 AlterNET Software.</auto-generated>

#pragma once

#include "Application.h"
#include "Keyboard.h"
#include "Mouse.h"
#include "Clipboard.h"
#include "Window.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API Application* Application_Create_()
{
    return MarshalExceptions<Application*>([&](){
        return new Application();
    });
}

ALTERNET_UI_API char16_t* Application_GetEventArgString_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetEventArgString());
    });
}

ALTERNET_UI_API char16_t* Application_GetName_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetName());
    });
}

ALTERNET_UI_API void Application_SetName_(Application* obj, const char16_t* value)
{
    MarshalExceptions<void>([&](){
        obj->SetName(value);
    });
}

ALTERNET_UI_API Keyboard* Application_GetKeyboard_(Application* obj)
{
    return MarshalExceptions<Keyboard*>([&](){
        return obj->GetKeyboard();
    });
}

ALTERNET_UI_API Mouse* Application_GetMouse_(Application* obj)
{
    return MarshalExceptions<Mouse*>([&](){
        return obj->GetMouse();
    });
}

ALTERNET_UI_API Clipboard* Application_GetClipboard_(Application* obj)
{
    return MarshalExceptions<Clipboard*>([&](){
        return obj->GetClipboard();
    });
}

ALTERNET_UI_API char16_t* Application_GetDisplayName_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetDisplayName());
    });
}

ALTERNET_UI_API void Application_SetDisplayName_(Application* obj, const char16_t* value)
{
    MarshalExceptions<void>([&](){
        obj->SetDisplayName(value);
    });
}

ALTERNET_UI_API char16_t* Application_GetAppClassName_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetAppClassName());
    });
}

ALTERNET_UI_API void Application_SetAppClassName_(Application* obj, const char16_t* value)
{
    MarshalExceptions<void>([&](){
        obj->SetAppClassName(value);
    });
}

ALTERNET_UI_API char16_t* Application_GetVendorName_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetVendorName());
    });
}

ALTERNET_UI_API void Application_SetVendorName_(Application* obj, const char16_t* value)
{
    MarshalExceptions<void>([&](){
        obj->SetVendorName(value);
    });
}

ALTERNET_UI_API char16_t* Application_GetVendorDisplayName_(Application* obj)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetVendorDisplayName());
    });
}

ALTERNET_UI_API void Application_SetVendorDisplayName_(Application* obj, const char16_t* value)
{
    MarshalExceptions<void>([&](){
        obj->SetVendorDisplayName(value);
    });
}

ALTERNET_UI_API c_bool Application_GetInUixmlPreviewerMode_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetInUixmlPreviewerMode();
    });
}

ALTERNET_UI_API void Application_SetInUixmlPreviewerMode_(Application* obj, c_bool value)
{
    MarshalExceptions<void>([&](){
        obj->SetInUixmlPreviewerMode(value);
    });
}

ALTERNET_UI_API c_bool Application_GetInvokeRequired_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetInvokeRequired();
    });
}

ALTERNET_UI_API void Application_SetGtkCss_(c_bool inject, const char16_t* css)
{
    MarshalExceptions<void>([&](){
        Application::SetGtkCss(inject, css);
    });
}

ALTERNET_UI_API PropertyUpdateResult Application_SetAppearance_(Application* obj, ApplicationAppearance appearance)
{
    return MarshalExceptions<PropertyUpdateResult>([&](){
        return obj->SetAppearance(appearance);
    });
}

ALTERNET_UI_API void Application_GetEventIdentifiers_(int* eventIdentifiers, int eventIdentifiersCount)
{
    MarshalExceptions<void>([&](){
        Application::GetEventIdentifiers(eventIdentifiers, eventIdentifiersCount);
    });
}

ALTERNET_UI_API void Application_ThrowError_(int value)
{
    MarshalExceptions<void>([&](){
        Application::ThrowError(value);
    });
}

ALTERNET_UI_API void Application_SetSystemOptionInt_(const char16_t* name, int value)
{
    MarshalExceptions<void>([&](){
        Application::SetSystemOptionInt(name, value);
    });
}

ALTERNET_UI_API void Application_Run_(Application* obj, Window* window)
{
    MarshalExceptions<void>([&](){
        obj->Run(window);
    });
}

ALTERNET_UI_API void* Application_GetTopWindow_(Application* obj)
{
    return MarshalExceptions<void*>([&](){
        return obj->GetTopWindow();
    });
}

ALTERNET_UI_API void Application_ExitMainLoop_(Application* obj)
{
    MarshalExceptions<void>([&](){
        obj->ExitMainLoop();
    });
}

ALTERNET_UI_API void Application_WakeUpIdle_()
{
    MarshalExceptions<void>([&](){
        Application::WakeUpIdle();
    });
}

ALTERNET_UI_API void Application_Exit_(Application* obj)
{
    MarshalExceptions<void>([&](){
        obj->Exit();
    });
}

ALTERNET_UI_API void Application_SuppressDiagnostics_(int flags)
{
    MarshalExceptions<void>([&](){
        Application::SuppressDiagnostics(flags);
    });
}

ALTERNET_UI_API void Application_BeginInvoke_(Application* obj, PInvokeCallbackActionType action)
{
    MarshalExceptions<void>([&](){
        obj->BeginInvoke(action);
    });
}

ALTERNET_UI_API void Application_ProcessPendingEvents_(Application* obj)
{
    MarshalExceptions<void>([&](){
        obj->ProcessPendingEvents();
    });
}

ALTERNET_UI_API c_bool Application_HasPendingEvents_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->HasPendingEvents();
    });
}

ALTERNET_UI_API void* Application_GetDisplayMode_(Application* obj)
{
    return MarshalExceptions<void*>([&](){
        return obj->GetDisplayMode();
    });
}

ALTERNET_UI_API c_bool Application_GetExitOnFrameDelete_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetExitOnFrameDelete();
    });
}

ALTERNET_UI_API int Application_GetLayoutDirection_(Application* obj)
{
    return MarshalExceptions<int>([&](){
        return obj->GetLayoutDirection();
    });
}

ALTERNET_UI_API c_bool Application_GetUseBestVisual_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetUseBestVisual();
    });
}

ALTERNET_UI_API c_bool Application_IsActive_(Application* obj)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->IsActive();
    });
}

ALTERNET_UI_API c_bool Application_SafeYield_(Application* obj, void* window, c_bool onlyIfNeeded)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->SafeYield(window, onlyIfNeeded);
    });
}

ALTERNET_UI_API c_bool Application_SafeYieldFor_(Application* obj, void* window, int64_t eventsToProcess)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->SafeYieldFor(window, eventsToProcess);
    });
}

ALTERNET_UI_API c_bool Application_SetDisplayMode_(Application* obj, void* videoMode)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->SetDisplayMode(videoMode);
    });
}

ALTERNET_UI_API void Application_SetExitOnFrameDelete_(Application* obj, c_bool flag)
{
    MarshalExceptions<void>([&](){
        obj->SetExitOnFrameDelete(flag);
    });
}

ALTERNET_UI_API c_bool Application_SetNativeTheme_(Application* obj, const char16_t* theme)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->SetNativeTheme(theme);
    });
}

ALTERNET_UI_API void Application_SetTopWindow_(Application* obj, void* window)
{
    MarshalExceptions<void>([&](){
        obj->SetTopWindow(window);
    });
}

ALTERNET_UI_API void Application_SetUseBestVisual_(Application* obj, c_bool flag, c_bool forceTrueColor)
{
    MarshalExceptions<void>([&](){
        obj->SetUseBestVisual(flag, forceTrueColor);
    });
}

ALTERNET_UI_API char16_t* Application_GetCustomData_(Application* obj, const char16_t* key)
{
    return MarshalExceptions<char16_t*>([&](){
        return AllocPInvokeReturnString(obj->GetCustomData(key));
    });
}

ALTERNET_UI_API void Application_SetEventCallback_(Application::ApplicationEventCallbackType callback)
{
    Application::SetEventCallback(callback);
}

