// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2022.</auto-generated>

#pragma once

#include "Application.h"
#include "Keyboard.h"
#include "Window.h"
#include "ApiUtils.h"

using namespace Alternet::UI;

ALTERNET_UI_API Application* Application_Create_()
{
    return new Application();
}

ALTERNET_UI_API Keyboard* Application_GetKeyboard_(Application* obj)
{
    return obj->GetKeyboard();
}

ALTERNET_UI_API void Application_Run_(Application* obj, Window* window)
{
    obj->Run(window);
}

ALTERNET_UI_API void Application_SetEventCallback_(Application::ApplicationEventCallbackType callback)
{
    Application::SetEventCallback(callback);
}

