// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2022.</auto-generated>

#pragma once


#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

