// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2023.</auto-generated>

#pragma once

#include "ColorPicker.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API ColorPicker* ColorPicker_Create_()
{
    return MarshalExceptions<ColorPicker*>([&](){
            return new ColorPicker();
        });
}

ALTERNET_UI_API Color_C ColorPicker_GetValue_(ColorPicker* obj)
{
    return MarshalExceptions<Color_C>([&](){
            return obj->GetValue();
        });
}

ALTERNET_UI_API void ColorPicker_SetValue_(ColorPicker* obj, Color value)
{
    MarshalExceptions<void>([&](){
            obj->SetValue(value);
        });
}

ALTERNET_UI_API void ColorPicker_SetEventCallback_(ColorPicker::ColorPickerEventCallbackType callback)
{
    ColorPicker::SetEventCallback(callback);
}

