// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2024 AlterNET Software.</auto-generated>

#pragma once

#include "ColorPicker.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API ColorPicker* ColorPicker_Create_()
{
    return new ColorPicker();
}

ALTERNET_UI_API Color_C ColorPicker_GetValue_(ColorPicker* obj)
{
    return obj->GetValue();
}

ALTERNET_UI_API void ColorPicker_SetValue_(ColorPicker* obj, Color value)
{
    obj->SetValue(value);
}

ALTERNET_UI_API void ColorPicker_SetEventCallback_(ColorPicker::ColorPickerEventCallbackType callback)
{
    ColorPicker::SetEventCallback(callback);
}

