// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2023.</auto-generated>

#pragma once

#include "DateTimePicker.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API DateTimePicker* DateTimePicker_Create_()
{
    return MarshalExceptions<DateTimePicker*>([&](){
            return new DateTimePicker();
        });
}

ALTERNET_UI_API DateTime_C DateTimePicker_GetValue_(DateTimePicker* obj)
{
    return MarshalExceptions<DateTime_C>([&](){
            return obj->GetValue();
        });
}

ALTERNET_UI_API void DateTimePicker_SetValue_(DateTimePicker* obj, DateTime value)
{
    MarshalExceptions<void>([&](){
            obj->SetValue(value);
        });
}

ALTERNET_UI_API int DateTimePicker_GetValueKind_(DateTimePicker* obj)
{
    return MarshalExceptions<int>([&](){
            return obj->GetValueKind();
        });
}

ALTERNET_UI_API void DateTimePicker_SetValueKind_(DateTimePicker* obj, int value)
{
    MarshalExceptions<void>([&](){
            obj->SetValueKind(value);
        });
}

ALTERNET_UI_API int DateTimePicker_GetPopupKind_(DateTimePicker* obj)
{
    return MarshalExceptions<int>([&](){
            return obj->GetPopupKind();
        });
}

ALTERNET_UI_API void DateTimePicker_SetPopupKind_(DateTimePicker* obj, int value)
{
    MarshalExceptions<void>([&](){
            obj->SetPopupKind(value);
        });
}

ALTERNET_UI_API void DateTimePicker_SetEventCallback_(DateTimePicker::DateTimePickerEventCallbackType callback)
{
    DateTimePicker::SetEventCallback(callback);
}

