// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2025 AlterNET Software.</auto-generated>

#pragma once

#include "GroupBox.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API GroupBox* GroupBox_Create_()
{
    return MarshalExceptions<GroupBox*>([&](){
        return new GroupBox();
    });
}

ALTERNET_UI_API int GroupBox_GetTopBorderForSizer_(GroupBox* obj)
{
    return MarshalExceptions<int>([&](){
        return obj->GetTopBorderForSizer();
    });
}

ALTERNET_UI_API int GroupBox_GetOtherBorderForSizer_(GroupBox* obj)
{
    return MarshalExceptions<int>([&](){
        return obj->GetOtherBorderForSizer();
    });
}

