// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2022.</auto-generated>

#pragma once

#include "InputStream.h"
#include "../ApiUtils.h"

using namespace Alternet::UI;

ALTERNET_UI_API void InputStream_SetTrampolineLocatorCallback(InputStream::TTrampolineLocatorCallback callback)
{
    InputStream::SetTrampolineLocatorCallback(callback);
}

