// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2022.</auto-generated>

#pragma once

#include "LinearGradientBrush.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API LinearGradientBrush* LinearGradientBrush_Create_()
{
    return MarshalExceptions<LinearGradientBrush*>([&](){
            return new LinearGradientBrush();
        });
}

ALTERNET_UI_API void LinearGradientBrush_Initialize_(LinearGradientBrush* obj, Point startPoint, Point endPoint, Color* gradientStopsColors, int gradientStopsColorsCount, double* gradientStopsOffsets, int gradientStopsOffsetsCount)
{
    MarshalExceptions<void>([&](){
            obj->Initialize(startPoint, endPoint, gradientStopsColors, gradientStopsColorsCount, gradientStopsOffsets, gradientStopsOffsetsCount);
        });
}

