// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2026 AlterNET Software.</auto-generated>

#pragma once

#include "MemoryFSHandler.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API MemoryFSHandler* MemoryFSHandler_Create_()
{
    return MarshalExceptions<MemoryFSHandler*>([&](){
        return new MemoryFSHandler();
    });
}

ALTERNET_UI_API void MemoryFSHandler_RemoveFile_(const char16_t* filename)
{
    MarshalExceptions<void>([&](){
        MemoryFSHandler::RemoveFile(filename);
    });
}

ALTERNET_UI_API void MemoryFSHandler_AddTextFileWithMimeType_(const char16_t* filename, const char16_t* textdata, const char16_t* mimetype)
{
    MarshalExceptions<void>([&](){
        MemoryFSHandler::AddTextFileWithMimeType(filename, textdata, mimetype);
    });
}

ALTERNET_UI_API void MemoryFSHandler_AddTextFile_(const char16_t* filename, const char16_t* textdata)
{
    MarshalExceptions<void>([&](){
        MemoryFSHandler::AddTextFile(filename, textdata);
    });
}

ALTERNET_UI_API void MemoryFSHandler_AddFile_(const char16_t* filename, void* binarydata, int size)
{
    MarshalExceptions<void>([&](){
        MemoryFSHandler::AddFile(filename, binarydata, size);
    });
}

ALTERNET_UI_API void MemoryFSHandler_AddFileWithMimeType_(const char16_t* filename, void* binarydata, int size, const char16_t* mimetype)
{
    MarshalExceptions<void>([&](){
        MemoryFSHandler::AddFileWithMimeType(filename, binarydata, size, mimetype);
    });
}

