// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2025 AlterNET Software.</auto-generated>
#pragma once
#include "ApiUtils.h"

namespace Alternet::UI
{
    #pragma pack(push, 1)
    struct DragEventData
    {
        void* data;
        float mouseClientLocationX;
        float mouseClientLocationY;
        DragDropEffects effect;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct CompareListViewItemsEventData
    {
        int64_t item1Index;
        int64_t item2Index;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct ListViewColumnEventData
    {
        int64_t columnIndex;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct ListViewItemLabelEditEventData
    {
        int64_t itemIndex;
        char16_t* label;
        c_bool editCancelled;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct TreeViewItemEventData
    {
        void* item;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct TreeViewItemLabelEditEventData
    {
        void* item;
        char16_t* label;
        c_bool editCancelled;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct WebBrowserEventData
    {
        char16_t* Url;
        char16_t* Target;
        int ActionFlags;
        char16_t* MessageHandler;
        c_bool IsError;
        char16_t* Text;
        int IntVal;
        void* ClientData;
    };
    #pragma pack(pop)
    
    #pragma pack(push, 1)
    struct MouseEventData
    {
        int mouseEventKind;
        int64_t timestamp;
        void* targetControl;
        int delta;
    };
    #pragma pack(pop)
    
}