// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2023 AlterNET Software.</auto-generated>

#pragma once

#include "NumericUpDown.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API NumericUpDown* NumericUpDown_Create_()
{
    return new NumericUpDown();
}

ALTERNET_UI_API c_bool NumericUpDown_GetHasBorder_(NumericUpDown* obj)
{
    return obj->GetHasBorder();
}

ALTERNET_UI_API void NumericUpDown_SetHasBorder_(NumericUpDown* obj, c_bool value)
{
    obj->SetHasBorder(value);
}

ALTERNET_UI_API int NumericUpDown_GetMinimum_(NumericUpDown* obj)
{
    return obj->GetMinimum();
}

ALTERNET_UI_API void NumericUpDown_SetMinimum_(NumericUpDown* obj, int value)
{
    obj->SetMinimum(value);
}

ALTERNET_UI_API int NumericUpDown_GetMaximum_(NumericUpDown* obj)
{
    return obj->GetMaximum();
}

ALTERNET_UI_API void NumericUpDown_SetMaximum_(NumericUpDown* obj, int value)
{
    obj->SetMaximum(value);
}

ALTERNET_UI_API int NumericUpDown_GetValue_(NumericUpDown* obj)
{
    return obj->GetValue();
}

ALTERNET_UI_API void NumericUpDown_SetValue_(NumericUpDown* obj, int value)
{
    obj->SetValue(value);
}

ALTERNET_UI_API void NumericUpDown_SetEventCallback_(NumericUpDown::NumericUpDownEventCallbackType callback)
{
    NumericUpDown::SetEventCallback(callback);
}

