// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2025 AlterNET Software.</auto-generated>

#pragma once

#include "Pen.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API Pen* Pen_Create_()
{
    return MarshalExceptions<Pen*>([&](){
        return new Pen();
    });
}

ALTERNET_UI_API void Pen_Initialize_(Pen* obj, DashStyle style, Color color, float width, LineCap lineCap, LineJoin lineJoin)
{
    MarshalExceptions<void>([&](){
        obj->Initialize(style, color, width, lineCap, lineJoin);
    });
}

