// <auto-generated>This code was generated by a tool, DO NOT MODIFY MANUALLY. Copyright AlterNET, 2023.</auto-generated>

#pragma once

#include "PrintDocument.h"
#include "PrinterSettings.h"
#include "PageSettings.h"
#include "DrawingContext.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API PrintDocument* PrintDocument_Create_()
{
    return new PrintDocument();
}

ALTERNET_UI_API c_bool PrintDocument_GetOriginAtMargins_(PrintDocument* obj)
{
    return obj->GetOriginAtMargins();
}

ALTERNET_UI_API void PrintDocument_SetOriginAtMargins_(PrintDocument* obj, c_bool value)
{
    obj->SetOriginAtMargins(value);
}

ALTERNET_UI_API char16_t* PrintDocument_GetDocumentName_(PrintDocument* obj)
{
    return AllocPInvokeReturnString(obj->GetDocumentName());
}

ALTERNET_UI_API void PrintDocument_SetDocumentName_(PrintDocument* obj, const char16_t* value)
{
    obj->SetDocumentName(value);
}

ALTERNET_UI_API PrinterSettings* PrintDocument_GetPrinterSettings_(PrintDocument* obj)
{
    return obj->GetPrinterSettings();
}

ALTERNET_UI_API PageSettings* PrintDocument_GetPageSettings_(PrintDocument* obj)
{
    return obj->GetPageSettings();
}

ALTERNET_UI_API DrawingContext* PrintDocument_GetPrintPage_DrawingContext_(PrintDocument* obj)
{
    return obj->GetPrintPage_DrawingContext();
}

ALTERNET_UI_API c_bool PrintDocument_GetPrintPage_HasMorePages_(PrintDocument* obj)
{
    return obj->GetPrintPage_HasMorePages();
}

ALTERNET_UI_API void PrintDocument_SetPrintPage_HasMorePages_(PrintDocument* obj, c_bool value)
{
    obj->SetPrintPage_HasMorePages(value);
}

ALTERNET_UI_API Rect_C PrintDocument_GetPrintPage_MarginBounds_(PrintDocument* obj)
{
    return obj->GetPrintPage_MarginBounds();
}

ALTERNET_UI_API Rect_C PrintDocument_GetPrintPage_PhysicalPageBounds_(PrintDocument* obj)
{
    return obj->GetPrintPage_PhysicalPageBounds();
}

ALTERNET_UI_API Rect_C PrintDocument_GetPrintPage_PageBounds_(PrintDocument* obj)
{
    return obj->GetPrintPage_PageBounds();
}

ALTERNET_UI_API Rect_C PrintDocument_GetPrintPage_PrintablePageBounds_(PrintDocument* obj)
{
    return obj->GetPrintPage_PrintablePageBounds();
}

ALTERNET_UI_API int PrintDocument_GetPrintPage_PageNumber_(PrintDocument* obj)
{
    return obj->GetPrintPage_PageNumber();
}

ALTERNET_UI_API void PrintDocument_Print_(PrintDocument* obj)
{
    obj->Print();
}

ALTERNET_UI_API void PrintDocument_SetEventCallback_(PrintDocument::PrintDocumentEventCallbackType callback)
{
    PrintDocument::SetEventCallback(callback);
}

