// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2026 AlterNET Software.</auto-generated>

#pragma once

#include "UnmanagedDataObject.h"
#include "UnmanagedStream.h"
#include "InputStream.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API UnmanagedDataObject* UnmanagedDataObject_Create_()
{
    return MarshalExceptions<UnmanagedDataObject*>([&](){
        return new UnmanagedDataObject();
    });
}

ALTERNET_UI_API NativeStringSpan_C UnmanagedDataObject_GetFormats_(UnmanagedDataObject* obj)
{
    return MarshalExceptions<NativeStringSpan_C>([&](){
        return obj->GetFormats();
    });
}

ALTERNET_UI_API NativeStringSpan_C UnmanagedDataObject_GetStringData_(UnmanagedDataObject* obj, NativeStringSpan* format)
{
    return MarshalExceptions<NativeStringSpan_C>([&](){
        return obj->GetStringData(*format);
    });
}

ALTERNET_UI_API NativeStringSpan_C UnmanagedDataObject_GetFileNamesData_(UnmanagedDataObject* obj, NativeStringSpan* format)
{
    return MarshalExceptions<NativeStringSpan_C>([&](){
        return obj->GetFileNamesData(*format);
    });
}

ALTERNET_UI_API UnmanagedStream* UnmanagedDataObject_GetStreamData_(UnmanagedDataObject* obj, NativeStringSpan* format)
{
    return MarshalExceptions<UnmanagedStream*>([&](){
        return obj->GetStreamData(*format);
    });
}

ALTERNET_UI_API void UnmanagedDataObject_SetStringData_(UnmanagedDataObject* obj, NativeStringSpan* format, NativeStringSpan* value)
{
    MarshalExceptions<void>([&](){
        obj->SetStringData(*format, *value);
    });
}

ALTERNET_UI_API void UnmanagedDataObject_SetFileNamesData_(UnmanagedDataObject* obj, NativeStringSpan* format, NativeStringSpan* value)
{
    MarshalExceptions<void>([&](){
        obj->SetFileNamesData(*format, *value);
    });
}

ALTERNET_UI_API void UnmanagedDataObject_SetStreamData_(UnmanagedDataObject* obj, NativeStringSpan* format, void* value)
{
    MarshalExceptions<void>([&](){
        obj->SetStreamData(*format, value);
    });
}

ALTERNET_UI_API c_bool UnmanagedDataObject_GetDataPresent_(UnmanagedDataObject* obj, NativeStringSpan* format)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetDataPresent(*format);
    });
}

ALTERNET_UI_API c_bool UnmanagedDataObject_GetNativeDataPresent_(UnmanagedDataObject* obj, int format)
{
    return MarshalExceptions<c_bool>([&](){
        return obj->GetNativeDataPresent(format);
    });
}

