// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2024 AlterNET Software.</auto-generated>

#pragma once

#include "Validator.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API Validator* Validator_Create_()
{
    return new Validator();
}

ALTERNET_UI_API void Validator_SuppressBellOnError_(c_bool suppress)
{
    Validator::SuppressBellOnError(suppress);
}

ALTERNET_UI_API c_bool Validator_IsSilent_()
{
    return Validator::IsSilent();
}

