// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2025 AlterNET Software.</auto-generated>

#pragma once

#include "ValidatorGeneric.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API ValidatorGeneric* ValidatorGeneric_Create_()
{
    #if !defined(__WXMSW__) || defined(_DEBUG)
    return MarshalExceptions<ValidatorGeneric*>([&](){
    #endif
        return new ValidatorGeneric();
    #if !defined(__WXMSW__) || defined(_DEBUG)
    });
    #endif
}

