// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2024 AlterNET Software.</auto-generated>

#pragma once

#include "ValidatorNumericProperty.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API ValidatorNumericProperty* ValidatorNumericProperty_Create_()
{
    return new ValidatorNumericProperty();
}

ALTERNET_UI_API void ValidatorNumericProperty_DeleteValidatorNumericProperty_(void* handle)
{
    ValidatorNumericProperty::DeleteValidatorNumericProperty(handle);
}

ALTERNET_UI_API void* ValidatorNumericProperty_CreateValidatorNumericProperty_(int numericType, int valBase)
{
    return ValidatorNumericProperty::CreateValidatorNumericProperty(numericType, valBase);
}

