using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Alternet.UI
{
    /// <summary>
    /// Choices used in <see cref="PropertyGrid"/> items for enum and flags properties.
    /// </summary>
    public interface IPropertyGridChoices
    {
        /// <summary>
        /// Gets <see cref="IPropertyGridChoices"/> object handle.
        /// </summary>
        IntPtr Handle { get; }

        /// <summary>
        /// Gets the number of elements actually contained in the <see cref="IPropertyGridChoices"/>.
        /// </summary>
        public int Count { get; }

        /// <summary>
        /// Adds new item.
        /// </summary>
        /// <param name="text">Item title.</param>
        /// <param name="value">Item value (id).</param>
        /// <param name="bitmap">Item image.</param>
        public void Add(string text, int value, ImageSet? bitmap = null);

        /// <summary>
        /// Adds new item with autogenerated id.
        /// </summary>
        /// <param name="text">Item title.</param>
        /// <returns>Item id.</returns>
        public int Add(string text);

        /// <summary>
        /// Adds the elements of the specified collection to the end.
        /// </summary>
        /// <param name="items">The collection whose elements should be added to the end.</param>
        public void AddRange(IEnumerable<string> items);

        /// <summary>
        /// Adds the elements of the specified collection to the end.
        /// </summary>
        /// <param name="items">The collection whose elements should be added to the end.</param>
        public void AddRange(IEnumerable<object> items);

        /// <summary>
        /// Searches for the specified item by it's title and returns value (id) of the item.
        /// </summary>
        /// <param name="text">Item title.</param>
        public int? GetValue(string text);

        /// <summary>
        /// Searches for the specified item by it's value and returns title of the item.
        /// </summary>
        /// <param name="value">Item value (id).</param>
        public string? GetText(int value);
    }
}
