// <auto-generated> DO NOT MODIFY MANUALLY. Copyright (c) 2026 AlterNET Software.</auto-generated>

#pragma once

#include "MessageBoxObj.h"
#include "Window.h"
#include "ApiUtils.h"
#include "Exceptions.h"

using namespace Alternet::UI;

ALTERNET_UI_API DialogResult MessageBoxObj_Show_(Window* owner, NativeStringSpan* text, NativeStringSpan* caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton)
{
    return MarshalExceptions<DialogResult>([&](){
        return MessageBoxObj::Show(owner, *text, *caption, buttons, icon, defaultButton);
    });
}

