<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>

<!-- https://www.nuget.org/packages/SkiaSharp/#versions-body-tab -->
<!-- https://www.nuget.org/packages/SkiaSharp.Extended/#versions-body-tab -->

<!--
	<SkiaSharpVersion>3.119.4</SkiaSharpVersion>
	<SvgSkiaVersion>5.1.1</SvgSkiaVersion>
-->
	<SkiaSharpVersion>4.151.1</SkiaSharpVersion>
	<SvgSkiaVersion>5.2.1</SvgSkiaVersion>

	<MicrosoftMauiVersion>10.0.71</MicrosoftMauiVersion>
	<CommunityToolkitMauiVersion>14.2.0</CommunityToolkitMauiVersion>
  </PropertyGroup>
</Project>