call run.sample.bat AnimationPlayer
call run.sample.bat Application
call run.sample.bat Border
call run.sample.bat Button
call run.sample.bat Calendar
call run.sample.bat CheckBox
call run.sample.bat CheckListBox
call run.sample.bat ColorPicker
call run.sample.bat ComboBox
call run.sample.bat ComboBoxAndLabel
call run.sample.bat DateTimePicker
call run.sample.bat DependencyProperty
call run.sample.bat DialogWindow
call run.sample.bat FindReplaceControl
call run.sample.bat Grid
call run.sample.bat GroupBox
call run.sample.bat Label
call run.sample.bat LayoutPanel
call run.sample.bat LinkLabel
call run.sample.bat ListBox
call run.sample.bat ListView
call run.sample.bat MiniFrameWindow
call run.sample.bat MultilineTextBox
call run.sample.bat NumericUpDown
call run.sample.bat PanelOkCancelButtons
call run.sample.bat PictureBox
call run.sample.bat ProgressBar
call run.sample.bat PropertyGrid
call run.sample.bat RadioButton
call run.sample.bat RichTextBox
call run.sample.bat RichToolTip
call run.sample.bat Slider
call run.sample.bat SpeedButton
call run.sample.bat SpeedTextButton
call run.sample.bat SplittedPanel
call run.sample.bat Splitter
call run.sample.bat StackPanel
call run.sample.bat TabControl
call run.sample.bat TextBox
call run.sample.bat TextBoxAndLabel
call run.sample.bat ToolBar
call run.sample.bat ToolBarSet
call run.sample.bat TreeView
call run.sample.bat WebBrowser
call run.sample.bat Window